name: Build

on:
  workflow_dispatch:
    inputs:

jobs:
  build-linux-x86_64:
    name: Build for Linux x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup build environment
        run: make setup-dev

      - name: Run tests
        run: make test

      - name: Build all artifacts
        run: make build

  build-linux-aarch64:
    name: Build for Linux AArch64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Setup, Test, Build
        run: make build-multiarch

#  build-linux-armv7:
#    name: Build for Linux ARMv7
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#
#      - name: Set up Docker Buildx
#        id: buildx
#        uses: docker/setup-buildx-action@v1
#        with:
#          version: latest
#
#      - name: Available platforms
#        run: echo ${{ steps.buildx.outputs.platforms }}
#
#      - name: Setup, Test, Build
#        run: PLATFORMS=linux/arm/v7 make build-multiarch

  build-macos:
    name: Build for MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup build environment
        run: make setup-dev

      - name: Run tests
        run: source ~/.bashrc && make test

      - name: Build all artifacts
        run: source ~/.bashrc && make build

  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Need to use this github action plugin to build vcpkg instead of using the one builtin in github action infra.
      # It will cause the following vcpkg packages build failed
      # Ref: https://github.com/OSSystems/compress-tools-rs/blob/master/.github/workflows/windows.yml#L28
      - name: Install vcpkg
        uses: lukka/run-vcpkg@v7
        with:
          setupOnly: true
          vcpkgGitCommitId: ec6fe06e8da05a8157dc8581fa96b36b571c1bd5 # 2020.11-1

      - name: Setup build environment
        run: ./hack/windows/setup-dev.ps1

      - name: Run tests
        run: cargo test --workspace --exclude=huber-generator

      - name: Build all artifacts
        run: cargo build --workspace --exclude=huber-generator